// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

const char ISSUE_YEAR[]       = SECRET_ISSUE_YEAR;
const char ISSUE_MONTH[]      = SECRET_ISSUE_MONTH;
const char ISSUE_DAY[]        = SECRET_ISSUE_DAY;
const char ISSUE_HOUR[]       = SECRET_ISSUE_HOUR;
const char EXPIRE_YEARS[]     = SECRET_EXPIRE_YEARS;
const char SERIAL_NUMBER[]    = SECRET_SERIAL_NUMBER;
const char AUTHORITY_KEY_ID[] = SECRET_AUTHORITY_KEY_ID;
const char SIGNATURE[]        = SECRET_SIGNATURE;

void onSecondsChange();

int seconds;

void initProperties(){

  ArduinoCloud.addProperty(seconds, READWRITE, ON_CHANGE, onSecondsChange);
  ArduinoCloud.updateCertificate(ISSUE_YEAR, ISSUE_MONTH, ISSUE_DAY, ISSUE_HOUR, EXPIRE_YEARS, SERIAL_NUMBER, AUTHORITY_KEY_ID,SIGNATURE);

}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
